#!/usr/bin/env bash

mc_port=25566
port=${1:-${PORT:-8080}}



# Start the TCP tunnel
chisel_cmd="./chisel server --port $port --proxy http://www.google.co.jp"
echo "Starting chisel..."
eval "$chisel_cmd > chisel.log &"
chisel_pid=$!

# Do an inline sync first, then start the background job
sync_pid=""
if [ "${AWS_ACCESS_KEY}" != "" ]; then 
  echo "Starting sync..."
  bin/sync
  eval "while true; do sleep ${AWS_SYNC_INTERVAL:-60}; bin/sync; done &"
  sync_pid=$!
fi

# create server config
echo "server-port=${mc_port}" >> /app/server.properties
touch whitelist.json
touch banned-players.json
touch banned-ips.json
touch ops.json

echo "Starting: minecraft ${mc_port}"
eval "java -jar minecraft.jar nogui &"
main_pid=$!

if [ "$sync_pid!" != "" ]; then
  trap "kill $chisel_pid $main_pid $sync_pid" SIGTERM
  trap "kill -9 $chisel_pid $main_pid $sync_pid; exit" SIGKILL
else
  trap "kill $chisel_pid $main_pid" SIGTERM
  trap "kill -9 $chisel_pid $main_pid; exit" SIGKILL
fi

